### ISSUE TITLE
[Bug]: Bug with the Border

### ISSUE THREAD

**Issue by PROMINeCRAFTER1** [Komaru-cats/WorldBorder-s-addon-for-BlazeandCave-s-Advancements-Pack#6]
### Describe your bug

So the bug is when you complete an achievement the border expand , but visually the border doesn't expand properly. So i hope in the near future this bug to be fixed. And also amazing mod pack. Good Luck.

### Version of datapack

1.21

**Comment by ItzSkyReed** [comment]
> but visually the border doesn't expand properly.

 what do you mean, can you describe it more or send screenshot/video?
