### ISSUE TITLE
[Question]: World Border Expansion

### ISSUE THREAD

**Issue by SnorkelStan** [Komaru-cats/WorldBorder-s-addon-for-BlazeandCave-s-Advancements-Pack#8]
### Ask your question here

I am trying to use this pack together with the blazeandcaves datapack to make a world where the border expands when you get an achievement (this works). The thing is, i want the border to expand by one block every time i get an achievement. Is there an in-game command for this, or do i have to dive into the files and change all of the values myself?

**Comment by ItzSkyReed** [comment]
You can't really do this without script, but there is a fork that adds something what you want https://github.com/tjthings/WorldBorder-BAC/releases

**Comment by ItzSkyReed** [comment]
Fork repo also has python script, so you can change that code to achieve the desired functionality you want
